### PR TITLE
Add filename options

### PR DESCRIPTION
**Pull request by colin-han**
Hi zetachang,

I add a new option 'filename' to your babel-plugin-dotenv package to allow user to customize the filename of .env file. For example, in my project, I change it to 'build.env'.

please review it.

### CODE REVIEW

**Comment by zetachang** [comment]
Hi, thanks for working on this. It looks great at first glance. Would you mind adding a test case?

**Comment by colin-han** [comment]
Ok, I will try to add some test case.

**Comment by colin-han** [comment]
I add a test case for it. Please review it again.

**Comment by colin-han** [comment]
@zetachang could you please publish a new version your package to NPM. Thus, I can use it in my project easily.  :-)

**Pull request merged**
